name = "polar"
license = "MIT"
licenselink = "https://github.com/am1t/hugo-polar/blob/master/LICENSE"
description = "Minimal theme with personality"
homepage = "http://amit-test.micro.blog/"
min_version = "0.41.0"

[author]
  name = "Amit Gawande"
  homepage = "https://mb.amitgawande.com"
